### ISSUE TITLE
Ensemble(last plot for ensemble) plotting(y_val, y_test, scope, avg_mae, WINDOW, PREDICTION_SCOPE)

### ISSUE THREAD

**Issue by CosmicQuant** [Hupperich-Manuel/LSTM-XGBoost#1]
I'm getting this below error for the prediction plot for the ensemble code :
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
[<ipython-input-105-3f24f25eccf7>](https://localhost:8080/#) in <module>()
----> 1 plotting(y_val, y_test, scope, avg_mae, WINDOW, PREDICTION_SCOPE)

[<ipython-input-5-c529d764d303>](https://localhost:8080/#) in plotting(y_val, y_test, pred_test, mae, WINDOW, PREDICTION_SCOPE)
     12 
     13     ploting_pred = [y_test[-1], pred_test]
---> 14     ploting_test = [y_val[-1]]+list(y_test)
     15 
     16     time = (len(y_val)-1)+(len(ploting_test)-1)+(len(ploting_pred)-1)

IndexError: index -1 is out of bounds for axis 0 with size 0

**Comment by manuhup** [comment]
Hi!,

It seems like the test df is empty, this can be because you changed the window to be too small so when you do the train/val-test split it does not get enough data, or there is an error in the code. Tell me if it works using a wider window, nevertheless, I will review the code and fix the errors that might occur.

Thank you!

**Comment by CosmicQuant** [comment]
Hi, sorry for the late reply. I did not change the window. but the window for xgboost is set 2 as from the code.  Should i increase the XGb window?

**Comment by CosmicQuant** [comment]
thank you

**Comment by manuhup** [comment]
Hi, 

I just committed some changes that seem to work.

One tip, run the code on Google Colab, it makes it much easier to work with. The code in the notebook was outdated compared to the one in the README, that's why it might not work.

Let me know if it works, otherwise, I will have a different look on it.

Thank you!!

**Comment by Daming8** [comment]
I am running the code in colab as well as in my local environment and I have this problem. I printed the changes for each step and the query to y_val is empty at the end, it has no data, I saved y_val from the above step. at the end it works.

**Comment by manuhup** [comment]
I've added some commits and a direct link to Google Colab so that it can be easily run.
Tell me if you continue to have issues! ;)

**Comment by Daming8** [comment]
已经收消息，谢谢。

**Comment by Daming8** [comment]
已经收消息，谢谢。
